// Generated By GitHub Copilot
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import request from 'supertest';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import type { DatabaseSchema } from '@tsm/shared';
import { createDb } from '../src/db.js';
import { createApp } from '../src/server.js';

const fixture: DatabaseSchema = {
  skills: [{ id: 'skl_typescript', name: 'TypeScript', category: 'Languages', targetLevel: 3 }],
  teams: [
    { id: 'team_platform', name: 'Platform' },
    { id: 'team_product', name: 'Product' },
  ],
  engineers: [
    { id: 'eng_alex', name: 'Alex', role: 'Engineer', teamId: 'team_platform' },
    { id: 'eng_bea', name: 'Bea', role: 'Designer', teamId: 'team_product' },
  ],
  assessments: [
    {
      engineerId: 'eng_alex',
      skillId: 'skl_typescript',
      level: 2,
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  resources: {},
};

describe('engineers API', () => {
  let app: ReturnType<typeof createApp>;
  let testDirectory: string | undefined;

  beforeEach(async () => {
    testDirectory = await mkdtemp(path.join(tmpdir(), 'tsm-engineers-'));
    const db = await createDb(path.join(testDirectory, 'db.json'));
    db.data = structuredClone(fixture);
    await db.write();
    app = createApp(db);
  });

  afterEach(async () => {
    if (testDirectory) await rm(testDirectory, { recursive: true, force: true });
    testDirectory = undefined;
  });

  it('lists engineers and filters them by team', async () => {
    const allEngineers = await request(app).get('/api/engineers').expect(200);
    const filteredEngineers = await request(app)
      .get('/api/engineers')
      .query({ teamId: 'team_product' })
      .expect(200);

    expect(allEngineers.body).toEqual(fixture.engineers);
    expect(filteredEngineers.body).toEqual([fixture.engineers[1]]);
  });

  it('gets an engineer and returns 404 for a missing engineer', async () => {
    const existing = await request(app).get('/api/engineers/eng_alex').expect(200);
    const missing = await request(app).get('/api/engineers/eng_missing').expect(404);

    expect(existing.body).toEqual(fixture.engineers[0]);
    expect(missing.body).toEqual({ error: 'Engineer not found' });
  });

  it('creates an engineer and persists it', async () => {
    const payload = { name: 'Casey', role: 'QA Engineer', teamId: 'team_platform' };

    const created = await request(app).post('/api/engineers').send(payload).expect(201);
    const engineers = await request(app).get('/api/engineers').expect(200);

    expect(created.body).toMatchObject(payload);
    expect(created.body.id).toMatch(/^eng_.{8}$/);
    expect(engineers.body).toContainEqual(created.body);
  });

  it('rejects invalid engineer data and an unknown team', async () => {
    const invalid = await request(app)
      .post('/api/engineers')
      .send({ name: '', role: 'Engineer', teamId: 'team_platform' })
      .expect(400);
    const unknownTeam = await request(app)
      .post('/api/engineers')
      .send({ name: 'Casey', role: 'QA Engineer', teamId: 'team_missing' })
      .expect(400);

    expect(invalid.body.error).toBeDefined();
    expect(unknownTeam.body).toEqual({ error: 'Unknown teamId' });
  });

  it('updates an engineer and returns errors for invalid or missing updates', async () => {
    const updated = await request(app)
      .put('/api/engineers/eng_alex')
      .send({ role: 'Senior Engineer' })
      .expect(200);
    const invalid = await request(app)
      .put('/api/engineers/eng_alex')
      .send({ name: '' })
      .expect(400);
    const missing = await request(app)
      .put('/api/engineers/eng_missing')
      .send({ role: 'Engineer' })
      .expect(404);

    expect(updated.body).toMatchObject({ ...fixture.engineers[0], role: 'Senior Engineer' });
    expect(invalid.body.error).toBeDefined();
    expect(missing.body).toEqual({ error: 'Engineer not found' });
  });

  it('deletes an engineer and dependent assessments', async () => {
    await request(app).delete('/api/engineers/eng_alex').expect(204);

    const engineers = await request(app).get('/api/engineers').expect(200);
    const assessments = await request(app)
      .get('/api/assessments')
      .query({ engineerId: 'eng_alex' })
      .expect(200);

    expect(engineers.body).toEqual([fixture.engineers[1]]);
    expect(assessments.body).toEqual([]);
  });

  it('returns 404 when deleting a missing engineer', async () => {
    const response = await request(app).delete('/api/engineers/eng_missing').expect(404);

    expect(response.body).toEqual({ error: 'Engineer not found' });
  });
});
