// Generated By GitHub Copilot
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import request from 'supertest';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import type { DatabaseSchema } from '@tsm/shared';
import { createDb } from '../src/db.js';
import { createApp } from '../src/server.js';

const fixture: DatabaseSchema = {
  skills: [
    {
      id: 'skl_typescript',
      name: 'TypeScript',
      category: 'Languages',
      description: 'Static typing for JavaScript.',
      targetLevel: 3,
    },
  ],
  teams: [{ id: 'team_platform', name: 'Platform' }],
  engineers: [{ id: 'eng_alex', name: 'Alex', role: 'Engineer', teamId: 'team_platform' }],
  assessments: [
    {
      engineerId: 'eng_alex',
      skillId: 'skl_typescript',
      level: 2,
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  resources: {},
};

describe('skills API', () => {
  let app: ReturnType<typeof createApp>;
  let testDirectory: string | undefined;

  beforeEach(async () => {
    testDirectory = await mkdtemp(path.join(tmpdir(), 'tsm-skills-'));
    const db = await createDb(path.join(testDirectory, 'db.json'));
    db.data = structuredClone(fixture);
    await db.write();
    app = createApp(db);
  });

  afterEach(async () => {
    if (testDirectory) await rm(testDirectory, { recursive: true, force: true });
    testDirectory = undefined;
  });

  it('lists all skills', async () => {
    const response = await request(app).get('/api/skills').expect(200);

    expect(response.body).toEqual(fixture.skills);
  });

  it('creates a skill with the supplied fields', async () => {
    const payload = {
      name: 'GraphQL',
      category: 'Backend',
      description: 'Query language for APIs.',
      targetLevel: 4,
    };

    const response = await request(app).post('/api/skills').send(payload).expect(201);
    expect(response.body).toMatchObject(payload);
    expect(response.body.id).toMatch(/^skl_.{8}$/);

    const skills = await request(app).get('/api/skills').expect(200);
    expect(skills.body).toContainEqual(response.body);
  });

  it('rejects invalid skill creation', async () => {
    const response = await request(app)
      .post('/api/skills')
      .send({ name: '', category: 'Backend', targetLevel: 5 })
      .expect(400);

    expect(response.body.error).toBeDefined();
  });

  it('updates an existing skill', async () => {
    const response = await request(app)
      .put('/api/skills/skl_typescript')
      .send({ description: 'Typed JavaScript.', targetLevel: 4 })
      .expect(200);

    expect(response.body).toMatchObject({
      id: 'skl_typescript',
      name: 'TypeScript',
      description: 'Typed JavaScript.',
      targetLevel: 4,
    });
  });

  it('returns 404 when updating a missing skill', async () => {
    const response = await request(app)
      .put('/api/skills/skl_missing')
      .send({ targetLevel: 4 })
      .expect(404);

    expect(response.body).toEqual({ error: 'Skill not found' });
  });

  it('deletes a skill and its assessments', async () => {
    await request(app).delete('/api/skills/skl_typescript').expect(204);

    const skills = await request(app).get('/api/skills').expect(200);
    expect(skills.body).toEqual([]);

    const assessments = await request(app)
      .get('/api/assessments')
      .query({ skillId: 'skl_typescript' })
      .expect(200);
    expect(assessments.body).toEqual([]);
  });

  it('returns 404 when deleting a missing skill', async () => {
    const response = await request(app).delete('/api/skills/skl_missing').expect(404);

    expect(response.body).toEqual({ error: 'Skill not found' });
  });
});
